# --------------------
# GitHub Action part-1
# --------------------

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask_deploy_ver${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  my_testing1:
    runs-on: ubuntu-latest
    env:
      VAR1: "This is job level variable 1"
      VAR2: "This is job level variable 2"

    steps:
      - name: Print env vars
        run: |
          echo "Var1=${{ env.VAR1}}"
          echo "Var2=${{ env.VAR2}}"
          echo "Var3=$LOCAL_VAR"
        env:
          LOCAL_VAR: "This is environment local viriable"
        
      - name: Print Hello World
        run: echo "Hello, world from testing1"
        
      - name: Excute few commands
        run: |
          echo "Hello message1"
          echo "Hello message2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: List current folder
        run: ls -la

  my_testing2:
    runs-on: ubuntu-latest
    needs: [my_testing1]

    steps:
      - name: Print Hello World
        run: echo "Hello, world from testing2"
