# --------------------
# GitHub Action part-1
# --------------------

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask_deploy_ver${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  my_testing1:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, world from testing1"
      - name: Excute few commands
        run: |
          echo "Hello message1"
          echo "Hello message2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
      - name: List current folder
        run: ls -la

  my_testing2:
    runs-on: ubuntu-latest
    needs: [my_testing1]

    steps:
      - name: Print Hello World
        run: echo "Hello, world from testing2"
