# --------------------
# GitHub Action part-1
# --------------------

name: My-GitHubActions-Basics
on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, world"
