# --------------------
# GitHub Action part-1
# --------------------

name: My-GitHubActions-Basics
on:
  push:
    branches:
      - main

jobs:
  my_testing1:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, world from testing1"

  my_testing2:
    runs-on: ubuntu-latest
    needs: [my_testing1]

    steps:
      - name: Print Hello World
        run: echo "Hello, world from testing2"
